(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "cask")
(depends-on "cider")
(depends-on "cider-decompile")
(depends-on "cider-tracing")
(depends-on "clojure-test-mode")
(depends-on "clojurescript-mode")
(depends-on "epl")
(depends-on "git")
(depends-on "git-gutter-fringe")
(depends-on "highlight-parentheses")
(depends-on "ido-yes-or-no")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "org")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "pkg-info")
(depends-on "rainbow-delimiters")
(depends-on "rhtml-mode")
(depends-on "rinari")
(depends-on "smart-mode-line")
(depends-on "smex")